/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class base_Jni */

#ifndef _Included_base_Jni
#define _Included_base_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     base_Jni
 * Method:    helloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_base_Jni_helloWorld
  (JNIEnv *, jobject);

/*
 * Class:     base_Jni
 * Method:    isPrime
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_base_Jni_isPrime
  (JNIEnv *, jobject, jint);

/*
 * Class:     base_Jni
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_base_Jni_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     base_Jni
 * Method:    divide
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_base_Jni_divide
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     base_Jni
 * Method:    pow
 * Signature: (DI)D
 */
JNIEXPORT jdouble JNICALL Java_base_Jni_pow
  (JNIEnv *, jobject, jdouble, jint);

/*
 * Class:     base_Jni
 * Method:    toUpcase
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_base_Jni_toUpcase
  (JNIEnv *, jobject, jstring);

/*
 * Class:     base_Jni
 * Method:    split
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_base_Jni_split
  (JNIEnv *, jobject, jstring);

/*
 * Class:     base_Jni
 * Method:    getList
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_base_Jni_getList
  (JNIEnv *, jobject);

/*
 * Class:     base_Jni
 * Method:    getPerson
 * Signature: ()Lbase/Jni/Person;
 */
JNIEXPORT jobject JNICALL Java_base_Jni_getPerson
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
