/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class base_Jni_Person */

#ifndef _Included_base_Jni_Person
#define _Included_base_Jni_Person
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
